### PR TITLE
CI Update test outputs

### PR DESCRIPTION
**Pull request by jarzec**
Updates outdated regression test output files.
Test failures to be addressed separately.

### CODE REVIEW

**Comment by JohelEGP** [comment]
#1291 addresses one such failure.

**Comment by jarzec** [comment]
> #1291 addresses one such failure.

Well, I was rather thinking about fixing the code than modifying the tests to make the faulty code pass.
There is actually an [LLVM bug](https://github.com/llvm/llvm-project/issues/108095) I've reported that affects all (almost all) the Clang versions we use. Nevertheless an elegant workaround modifying the code itself seems achievable.

**Comment by JohelEGP** [comment]
> Well, I was rather thinking about fixing the code than modifying the tests to make the faulty code pass.
> There is actually an [LLVM bug](https://github.com/llvm/llvm-project/issues/108095) I've reported that affects all (almost all) the Clang versions we use.

I do wonder.

I noticed this while working on #526,
before requiring parameters to be named `_`,
and lowering only the parameter's type.

I'm fairly sure that, at the time,
I checked with the C++ Standard whether Clang was right.
I think I found out Clang was indeed right,
and as a result I opened no compiler bugs.

**Comment by jarzec** [comment]
Outdated, replaced with #1324

**Pull request closed without merging**
