### PR TITLE
Added automated passthrough and regression unit tests.

### PR DESCRIPTION
**Pull request by wingunder**
Running the unit tests can be achieved by running 'make check' in the
top-level directory. Cleaning up of any unit test artifacts can be
achieved by running 'make clean'.
    
Detailed documentation can be found in README_unit_tests.md.

Note that the following 2 commits from @knst had to be used as base, as this change relies on proper return values from `cppfront`.      These commits have not been merged into the `main` branch.

   commit 3d1a5933
   commit 8a84c4f9

### CODE REVIEW

**Comment by knst** [comment]
Check this one: [fix typo in Makefile: exceeding tab for BATS](https://github.com/knst/cppfront/commit/21aa0ff262966123e865340dfa0241f2808d91b7)

**Comment by wingunder** [comment]
> Check this one: [fix typo in Makefile: exceeding tab for BATS](https://github.com/knst/cppfront/commit/21aa0ff262966123e865340dfa0241f2808d91b7)

Thanks. I just cherry-picked your fix-commit.

**Comment by hsutter** [comment]
Thanks! I appreciate it and want to automate this at some point in the future, but I'm trying hard to avoid dependencies (make, Cmake, ...). So although tests that are manually run with a batch/shell script or two have drawbacks and some manual work, I'm inclined to stick with them as good enough for now. Sorry! but also thanks again, this is something I want to look at again later when things are more complete.

**Comment by wingunder** [comment]
> Thanks! I appreciate it and want to automate this at some point in the future, but I'm trying hard to avoid dependencies (make, Cmake, ...). So although tests that are manually run with a batch/shell script or two have drawbacks and some manual work, I'm inclined to stick with them as good enough for now. Sorry! but also thanks again, this is something I want to look at again later when things are more complete.

You're welcome. No problem :)

**Pull request closed without merging**
