### PR TITLE
Bugfix #778: Flag for entry into for loop after range has been processed

### LINKED ISSUE #778: [BUG] Passing lambda to function call of for loop causes incorrect uninitialized variable error
**Describe the bug**
Passing a lambda to a for loop parameter's function call produces an incorrect "use before initialization" error.

**To Reproduce**
Sample code:
```
first: (forward f, forward _...) -> forward _ = f;

main: () = {
   ints: const std::array = (1, 2, 3, 4, 5);
   // OK
   for ints.first() do (i) {
      std::cout << i;
   }

   // OK
   for ints.first(1) do (i) {
      std::cout << i;
   }

   // Error
   for ints.first(:(x) x) do (i) {
      std::cout << i;
   }

   // OK
   temp := ints.first(:(x) x);
   for temp do (i) {
      std::cout << i;
   }
}
```

Commands:
```
./cppfront test.cpp2
```

Expected result:
Program compiles without error.

Actual result/error:
```
test.cpp2...
test.cpp2(17,20): error: local variable i is used before it was initialized
  ==> program violates initialization safety guarantee - see previous errors
```

**Additional context**
I found this while trying to use `std::views::filter` and this seems to be the root cause of the error.

### PR DESCRIPTION
**Pull request by fknauf**
Fixes #778, and it's possibly relevant for #432.

I ran the regression tests and spotted no differences in output. I also have a bash script now to run the tests on a Linux machine, should I put that in here as well?

### CODE REVIEW

**Review by JohelEGP — APPROVED** [review]
Thank you.
The approach looks correct to me.
Can you add these tests for confirmation?
```Cpp2
issue_778: (args) = {
   for :() args$;() do (i) _ = i;
   for :(x) x;(args) do (j) _ = j;
   for :(x) x;(args) next _ = :() args$;() do (k) _ = k;
   for :(x) x;(args) next _ = :(x) x;(args) do (l) _ = l;
}
```

**Comment by fknauf** [comment]
I added the tests. The output was compileable and looked reasonable to me. Then I merged the new state of the main branch and ran the tests again. All tests are green, so it seems to work and not break anything.

**Comment by fknauf** [comment]
I'm not 100% sure I agree that flags like this one are the correct way to handle parsing context like this, but it seemed like the least invasive way to handle it. In a new design I'd maybe consider encoding information like this in the parse tree so that the safety of the expression becomes an S-attribute.

**Comment by hsutter** [comment]
(Catching up with PRs, sorry for the delay)

Thanks for your pull request! It looks like this may be your first contribution to cppfront. I've sent the Contributor License Agreement (CLA) to your email, and once it's signed I can look at your pull request. Thanks again for your contribution.

**Comment by hsutter** [comment]
Thanks! I just made a minor style tweak to follow the style I was already using for such so-far-very-occasional extra information.

**Pull request merged**
