### PR TITLE
Add version and build of cppfront to generated files.

### PR DESCRIPTION
**Pull request by iprtel**
I would find it useful to track which version of cppfront generated a .cpp or .h file.

### CODE REVIEW

**Comment by hsutter** [comment]
(Catching up with PRs, sorry for the delay)

Thanks for your pull request! It looks like this may be your first contribution to cppfront. I've sent the Contributor License Agreement (CLA) to your email, and once it's signed I can look at your pull request. Thanks again for your contribution.

**Comment by hsutter** [comment]
Update: I tried sending it to your email in the commit, but it wasn't deliverable. Please just send me an email so I have your current address and I'll resend the CLA. Thanks.

**Comment by iprtel** [comment]
Hello,
 
I'm sorry that the email did not work. This is my regular email address.
Please send the CLA here. Thank you.
 
Regards,
Ingo

**Comment by hsutter** [comment]
Thanks! I added a flag so that it's opt-in, because likely users won't want this to generate extra diffs just because they updated their compiler.

I noticed that there seemed to be a large diff conflict, and unfortunately when I tried to resolve the conflict it seems to have lost the code change, and when I went back into the branch to restore it git wanted me to pull over 60 commits. I wonder if something got broken, and you should regenerate this PR? Sorry for the busywork, I appreciate the suggestion!

**Comment by iprtel** [comment]
I had to 'manually cherry pick' your commit. Sorry about that.

**Comment by hsutter** [comment]
Thanks!

**Pull request merged**
