### PR TITLE
Fix typos in contracts.md

### PR DESCRIPTION
**Pull request by bluetarpmedia**
Fix some small typos

### CODE REVIEW

**Comment by bluetarpmedia** [comment]
Just realised I applied this to the `docs` branch instead of `main`, is that okay?

**Comment by hsutter** [comment]
Right, I just merged `main` but I didn't finish going through the PRs for `docs`.

My plan was to manually merge those to `main` in the next few days, but if you want to retarget this PR to `main` that would be fine too!

**Comment by bluetarpmedia** [comment]
Changed PR target branch to `main`.

**Comment by hsutter** [comment]
Thanks!

**Pull request merged**
