### PR TITLE
Digit separator doesn't parse with opening brace

### LINKED ISSUE #862: [BUG] Digit separator doesn't parse
<a id="title"/>

**[T](#title)itle**: Digit separator doesn't parse.

<a id="rep"/>
<a id="cpp2"/>

**[M](#rep)inimal reproducer** (<https://cpp2.godbolt.org/z/Pn4zd7MeM>):

```Cpp2
niam: () = { _ = 0'1; } // Not OK.
main: () = {
  _ = 0'1; // OK
}
```

<a id="cmd"/>
<details><summary>
<b><a href="#cmd">C</a>ommands</b>:
</summary>

```bash
cppfront main.cpp2
clang++18 -std=c++23 -stdlib=libc++ -lc++abi -pedantic-errors -Wall -Wextra -Wconversion -Werror=unused-result -Werror=unused-value -Werror=unused-parameter -I . main.cpp
```
</details>

<a id="expected"/>

**[E](#expected)xpected result**: Both to work.

<a id="actual"/>

**[A](#actual)ctual result and error**:

```output
main.cpp2...
main.cpp2(5,0): error: end of file reached with 1 missing } to match earlier { on line 1
```

### PR DESCRIPTION
**Pull request by ntrel**
Fixes #862.

### CODE REVIEW

**Comment by ntrel** [comment]
Note that keeping Cpp1 apostrophe as digit separator caused this parsing complication. Personally I think underscore reads much nicer and wouldn't need special tracking here.

**Comment by JohelEGP** [comment]
The last point of <https://github.com/hsutter/cppfront/issues/289#issuecomment-1480594843> also addresses a comment about using something other than `'` as a digit separator.

**Comment by gregmarr** [comment]
@ntrel It's possible that underscore would conflict with user defined literals.

**Comment by JohelEGP** [comment]
Not really.
`0_0` separates.
`0_d` UDLs.

**Comment by SebastianTroy** [comment]
Now that there is no comma operator, could comma be used instead?


On 8 December 2023 16:55:28 gregmarr ***@***.***> wrote:

@ntrel<https://github.com/ntrel> It's possible that underscore would conflict with user defined literals.

**Comment by SebastianTroy** [comment]
Oof, yeah how could I have missed such a blatant ambiguity...


On 8 December 2023 17:42:28 Johel Ernesto Guerrero Peña ***@***.***> wrote:

No.
For ambiguities, see https://www.reddit.com/r/cpp/comments/18canwt/small_rant_the_comma_operator_is_one_of_the_worst/.
One example is f(1,2).
Is that 12, or 1 and 2?

**Comment by JohelEGP** [comment]
#862 was fixed by commit fb820ebf8d3130498d3b3de4881987ae08722855.

**Comment by hsutter** [comment]
Thanks for this! I appreciate the PR, but I ended up fixing it a different way (using a shortcut to try not to duplicate as much of numeric literal parsing during brace matching, but if we discover problems with that we can look at this PR again). Again, thanks very much.

**Pull request closed without merging**
