### PR TITLE
Adds CMake support

### PR DESCRIPTION
**Pull request by mordante**
Adds a simple CMake script and makes the tests portable with both Windows and Linux support.

### CODE REVIEW

**Comment by mordante** [comment]
Note there's some overlap with #21, but these tests Linux tests are closer to the batch tests. (I noticed you want to rework them @hsutter, but I needed something to test on Linux,)

**Comment by hsutter** [comment]
As with #4 and #15 and similar, for now I'd be happy to link to a sister project from [the wiki](https://github.com/hsutter/cppfront/wiki).

If you make this a sister project, let me know the link and description I should use. Thanks!

**Comment by alexreinking** [comment]
This was already attempted in #15, which was reworked into [modern-cmake/cppfront](https://github.com/modern-cmake/cppfront) (and is mentioned in the wiki of this repository) and is a much more complete implementation.

**Comment by alexreinking** [comment]
There are a lot of problems with the implementation here, ranging from the misuse of `CMAKE_BINARY_DIR` to the overcomplicated configuration of the test runner script.

I encourage you to use the modern-cmake/cppfront repo, which is friendly to `add_subdirectory` and FetchContent, has `find_package` support, and a CTest-based test harness.

**Pull request closed without merging**
