### PR TITLE
CI Update tests after recent modifs

### PR DESCRIPTION
**Pull request by jarzec**
As stated in the title.
When this PR is merged I will rebase #1250 to ensure everything is green and ready for merging.

### CODE REVIEW

**Comment by JarekGlobus** [comment]
@hsutter This PR will turn all tests except `mixed-type-safety-1.cpp2` green.
I've rebased #1250 on this one, so you can merge this one first and #1250 right after.
Unfortunately, what seems to be a bug in GCC 10 manifesting in `mixed-type-safety-1.cpp2` will require further investigation.
The good thing is that after #1250 this test will start to work for C++23.

**Comment by jarzec** [comment]
@hsutter This PR will turn all tests except `mixed-type-safety-1.cpp2` green.
I've rebased #1250 on this one, so you can merge this one first and #1250 right after.
Unfortunately, what seems to be a bug in GCC 10 manifesting in `mixed-type-safety-1.cpp2` will require further investigation.
The good thing is that after #1250 this test will start to work for C++23.

**Comment by jarzec** [comment]
@hsutter After rebasing this PR on your recent changes and applying patches this PR already makes all the tests green.

**Comment by hsutter** [comment]
Thanks!

**Pull request merged**
