### PR TITLE
[SUGGESTION][FIX] Add support for raw string literals in mixed mode

### PR DESCRIPTION
**Pull request by filipsajdak**
Current implementation in mixed mode is not parsing raw string literals well.

Cpp2 source code
```cpp
auto r = R"(
    this is raw string literal
    \n
    /*   */
    //
i: int = 42;
)";

/*
 *
 *   this is a comment
 *
 */

main: () -> int = {
    std::cout << "Hello world\n\n" << std::quoted(r) << std::endl;
}
```
Compiles to
```cpp
// ----- Cpp2 support -----
#include "cpp2util.h"

#line 1 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"

auto r = R"(
    this is raw string literal
    \n
    /*   */
    //

#line 7 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"
#line 8 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"
)";

#line 16 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"
[[nodiscard]] auto main() -> int;

//=== Cpp2 definitions ==========================================================

#line 7 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"
int i { 42 }; 
#line 9 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"

/*
 
    this is a comment
 
 */

[[nodiscard]] auto main() -> int{
    std::cout << "Hello world\n\n" << std::quoted(r) << std::endl;
}
```

The proposed change makes cppfront parse raw string literals in a similar way as it parses `/* */` comments. After this change cppfront produces:
```cpp
// ----- Cpp2 support -----
#include "cpp2util.h"

#line 1 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"

auto r = R"(
    this is raw string literal
    \n
    /*   */
    //
i: int = 42;
)";

#line 16 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"
[[nodiscard]] auto main() -> int;

//=== Cpp2 definitions ==========================================================

#line 9 "/Users/filipsajdak/dev/execspec/external/tests/raw_string.cpp2"

/*
 
    this is a comment
 
 */

[[nodiscard]] auto main() -> int{
    std::cout << "Hello world\n\n" << std::quoted(r) << std::endl;
}
```
Debug info shows that the lines are recognized as `/* R */` which was added symbol to mark raw string literals lines.
```
/*   */ 
/* 1 */ auto r = R"(
/* R */     this is raw string literal
/* R */     \n
/* R */     /*   */
/* R */     //
/* R */ i: int = 42;
/* 1 */ )";
/* 2 */ 
/* 2 */ /*
/* 2 */  *
/* 2 */  *   this is a comment
/* 2 */  *
/* 2 */  */
/* 2 */ 
/* 2 */ main: () -> int = {
/* 2 */     std::cout << "Hello world\n\n" << std::quoted(r) << std::endl;
/* 2 */ }
```

Close https://github.com/hsutter/cppfront/issues/62

### CODE REVIEW

**Comment by filipsajdak** [comment]
In the last push, I have added also support for `d-char-sequence` from spec:
```
prefix(optional) R"d-char-sequence(optional)
(r-char-sequence(optional))d-char-sequence(optional)"
```
The only thing I did not check yet is the prefix.

The current implementation can handle:
```cpp
auto r = R"abc(
    this is raw string literal
    \n
    /*   */
    //
i: int = 42;
)abc";
```

**Comment by filipsajdak** [comment]
I have tested the prefixes and it seems to work, too.

**Comment by hsutter** [comment]
I actually completely forgot about raw string literals... thanks for doing this. At first blush this looks good, before merging let me take a deeper look with a fresh brain and a fresh cup of coffee...

Did you check the three `/passthrough-tests` files to make sure they still are diff-identical when passed through cppfront?

**Comment by filipsajdak** [comment]
No, unfortunately I did not do this. 

Will check that.

**Comment by JohelEGP** [comment]
I think https://github.com/modern-cmake/cppfront does that.

**Comment by filipsajdak** [comment]
I have rebased my changes to the main and done the passthrough tests.

clang & GCC files are the same.

MSVC ends with the error:
```
cppfront % ../../build/external/cppfront passthrough-tests/msvc-msstl-e.cpp2      
passthrough-tests/msvc-msstl-e.cpp2...
msvc-msstl-e.cpp2(174324,0): error: closing } does not match a prior {
```

Need to check what caused the error.

**Comment by filipsajdak** [comment]
OK, found a bug and fix it.

The issue was here
```diff
diff --git a/source/load.h b/source/load.h
index 71fd857..9954a02 100644
--- a/source/load.h
+++ b/source/load.h
@@ -248,7 +248,7 @@ auto process_cpp_line(
                 return r;
             }
             in_raw_string_literal = false;
-            i += end_pos+d_char_sequence.size()-1;
+            i = end_pos+d_char_sequence.size()-1;
         }
         else {
             r.all_comment_line = false;
```

Small but nasty mistake. Now all files compiles and generate identical output.

**Comment by filipsajdak** [comment]
Rebased to main - all passthrough-tests and regression-tests passed.

**Comment by hsutter** [comment]
I tried this out with the `passthrough-tests`, starting with running `cppfront msvc-msstl-e.cpp2`, but it crashed.

Running it under the debugger, I see that the crash is an out-of-bounds access attempt in the second-last line in `process_cpp_line`:

    prev = line[i];

where `i` was about 20-30 higher than `line.size()`.

I didn't investigate further, but this should give you a repro and a roadmap to find the bug... can you take a look?

**Comment by filipsajdak** [comment]
Hmm... I am surprised that it crashed. I will investigate

**Comment by filipsajdak** [comment]
The interesting fact is that only MSVC is using raw string literals in its lib. It is always inline and finalised with the string_view suffix. E.g.:
```cpp
_Result += R"(: ")"sv;
```
so `d_char_sequence` will be empty.

**Comment by filipsajdak** [comment]
@hsutter I have rebased my changes on the newest main and still cannot reproduce. I will probably need to check on other compilers.

**Comment by filipsajdak** [comment]
@hsutter I am confused. I have tried it on MSVC and it works as well. I will need more information To be able to reproduce it. 

My very first guess is that it looks like the previous bug that I have fixed (check above). Some merge issues might also cause it.

**Comment by hsutter** [comment]
OK, I'll take another look. Thanks!

**Comment by filipsajdak** [comment]
@hsutter if it will not work, please send me the code you have via email I will verify what is wrong.

**Comment by hsutter** [comment]
Good news: It works fine!

The test failure was almost certainly my error when I opened the branch in GitHub Desktop and must just not have had all the latest commits somehow. (I did try pulling the later commits, but there was a conflict and I'm just not familiar enough with GitHub Desktop.)

So I have verified the PR by the time-honored method of manually applying it to my main branch and running the passthrough tests, and they work fine. So now I'll revert that and merge this PR. :) Thanks again.

**Comment by filipsajdak** [comment]
Happy to hear that it's working.

The good thing is that this situation motivated me to run sanitizers which helped in discovering another issue.

**Pull request merged**
