### PR TITLE
CI Remove empty test reference files

### PR DESCRIPTION
**Pull request by jarzec**
- Update the `run-tests.sh`.
  - Handle empty generated files as correct without the need for committing them.
  - Remove such files generated by the test.
  - Report empty reference files as errors to maintain the status quo.
- Add a `rm-empty-files.sh` utility script for removing all empty files in current directory.
- Remove all empty reference test files (>1500 empty files less in the repository).

Note: This PR is one step towards improvements of the kind proposed in #1137. It should make further improvement simpler.
An iterative approach should be easier to handle.

### CODE REVIEW

**Comment by jarzec** [comment]
The test failures will be fixed by #1165.

**Comment by hsutter** [comment]
Thanks!

**Comment by jarzec** [comment]
@hsutter  My last update of this PR was missing some changes from main and is now causing test failures.
I am working on a fix in #1176 - it should become all green soon.

**Comment by hsutter** [comment]
Hmm... one thing I meant to ask before merging this (but forgot, sorry) was:

Early on, the reason I was storing files even if empty was because otherwise I couldn't distinguish between "test ran successfully and there was no output" and "test crashed and failed to generate any output."

Are we still going to catch the "empty" vs "crashed" case somehow so that we don't start getting silent regressions due to crashes for test cases that would have empty output anyway?

**Comment by jarzec** [comment]
That is a good point. The test script currently silently removes the generated empty file. I will add a check that the file actually got created.

**Pull request merged**
