### PR TITLE
Update regression tests after recent changes

### PR DESCRIPTION
**Pull request by bluetarpmedia**

### CODE REVIEW

**Comment by hsutter** [comment]
I hand-resolved that MSVC regex-10.execution file, it might not be quite right but for some reason it was sticking in my local GitHub environment's throat (it appeared to be a change I couldn't discard), so I just committed and pushed it and hand-resolved the conflict in this merge.

**Comment by MaxSagebaum** [comment]
@bluetarpmedia Since you always do the regression updates. I just wanted to ask if there is any easy way to get all the diffs. Checking every version, searching for diff and then copying it out, is quite cumbersome. Is there an automated way to get all the diffs of all runners?

**Comment by bluetarpmedia** [comment]
Yes, @jarzec modified the CI pipeline to create a handy aggregate of all the failed diffs.

Eg scroll down on this Summary page:
https://github.com/hsutter/cppfront/actions/runs/10327301935

Download the aggregate zip file, unzip into your cppfront directory and then `git apply` each diff file.

**Comment by DyXel** [comment]
You probably can automate further with the Github CLI tool and/or a combination of scripts that uses Github APIs, probably something to look for in the future if more toolchains/targets are added.

**Comment by MaxSagebaum** [comment]
Ah thank. That helped alot.

**Pull request merged**
